[package]
name = "ryosys"
version = "0.1.0"
edition = "2024"

[build-dependencies]
bindgen = { git = "https://github.com/nickrallison/rust-bindgen.git" }
#bindgen = { path = "../rust-bindgen/bindgen" }
regex = "1.11.1"

[dependencies]
